[package]
name = "rusty-cute-macros"
version = "0.1.0"
authors = ["DoumanAsh <custparasite@gmx.se>"]
description = "Bunch of lazy macros which i used from time to time"
repository = "https://github.com/DoumanAsh/rusty-cute-macros"
license = "MIT"
